name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        run: sudo apt update && sudo apt install openjdk-21-jre-headless -y

      - name: Download Playit
        run: |
          wget https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64
          chmod +x playit-linux-amd64

      - name: Run Playit
        run: ./playit-linux-amd64 &

      - name: Start Minecraft Server
        run: java -Xmx4G -Xms2G -jar paper-1.21.11-126.jar nogui
